version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: